# version: 2
# updates:
#   # Frontend dependencies
#   - package-ecosystem: "npm"
#     directory: "/frontend"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#       time: "09:00"
#     open-pull-requests-limit: 10
#     reviewers:
#       - "your-github-username" # Replace with actual username
#     assignees:
#       - "your-github-username" # Replace with actual username
#     commit-message:
#       prefix: "deps(frontend)"
#       include: "scope"
#     labels:
#       - "dependencies"
#       - "frontend"
#     ignore:
#       # Ignore major version updates for specific packages if needed
#       - dependency-name: "react"
#         update-types: ["version-update:semver-major"]

#   # Backend dependencies
#   - package-ecosystem: "pip"
#     directory: "/backend"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#       time: "09:00"
#     open-pull-requests-limit: 10
#     reviewers:
#       - "your-github-username" # Replace with actual username
#     assignees:
#       - "your-github-username" # Replace with actual username
#     commit-message:
#       prefix: "deps(backend)"
#       include: "scope"
#     labels:
#       - "dependencies"
#       - "backend"

#   # GitHub Actions
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "monthly"
#       day: "monday"
#       time: "09:00"
#     commit-message:
#       prefix: "ci"
#       include: "scope"
#     labels:
#       - "dependencies"
#       - "github-actions"
